import bowl from '../assets/bowls.png'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import HomeNavBar from './HomeNavBar'
import Pizza from '../assets/Pizza.jpg'
import Biriyani from '../assets/Biriyani.jpg'
import Pasta from '../assets/Pasta.jpg'
import Tiramisu from '../assets/Tiramisu.jpg'
import { IoIosClose } from "react-icons/io";
  const Foods=[
        {
            image:Pizza,
            title:"Pizza",
            description:"An Italian classic featuring a baked dough base topped with savory tomato sauce, melted cheese, and assorted toppings."
        },
        {
            image:Biriyani,
            title:"Biriyani",
            description:" A rich, South Asian spiced dish made by slow-cooking layered long-grain Basmati rice with marinated meat or vegetables"
        },
        {
            image:Pasta,
            title:"Pasta",
            description:" A versatile Italian staple made from wheat dough, shaped into varieties like spaghetti or penne, and tossed in rich sauces"
        },
        {
            image:Tiramisu,
            title:"Tiramisu",
            description:" A versatile Italian staple made from wheat dough, shaped into varieties like spaghetti or penne, and tossed in rich sauces"
        }
    ]

function Home(){
    const[selectedFood,setSelectedFood]=useState(null)
    const navigate=useNavigate()
  
    return(
        <div className='min-h-screen   bg-[#D3EEE1] pt-8 p-6  relative'>
          <HomeNavBar/>
          <div className=' flex flex-col lg:flex-row items-center  lg:px-16 px-6 py-10'>
    

      
            <div className='w-full  text-center lg:w-1/2  lg:text-left space-y-8'>
                <h1 className='font-extrabold text-5xl  md:text-6xl lg:text-7xl   '> Discover
  <span className=" text-5xl md:text-6xl text-[#297B41] leading-tight"> Recipes</span>
  <br />
  With AI</h1>
                
                <p className='max-w-md text-lg lg:mx-0 mx-auto text-gray-600'>Search any dish and instantly get ingredients, instructions, and cooking tips generated by AI.</p>
                
                <div className='hidden lg:flex flex flex-col sm:flex-row  justify-center gap-6 lg:justify-start'>
                <button className='bg-[#297B41] md:py-2 px-12 rounded-full text-white hover:bg-[#D3EEE1] hover:border-2 border-[#297B41] hover:text-[#297B41] transition-all duration-300' onClick={()=>navigate("/signup")}>Get Started</button>
                <button className='border-2 border-[#297B41] text-[#297B41] py-2 px-12 rounded-full  hover:bg-[#297B41] hover:text-white transition-all duration-300' onClick={()=>navigate("/login")}> Log in</button>
                </div>
                <p className="text-md text-gray-500">
                     ✨ Generate recipes in seconds
                 </p>
            </div>
            <div className='w-full lg:w-1/2 flex justify-center my-10 lg:my-0 relative  '>
          
                
                <img src={bowl} alt="Food bowl" className=' max-w-[500px] lg:w-[500px] w-full sm:w-80 rounded-full drop-shadow-lg md:[filter:drop-shadow(-35px_35px_20px_rgba(0,0,0,0.25))]'></img>
            </div>
             
              <div className=' lg:hidden flex flex-col sm:flex-row  gap-4 justify-center lg:justify-start'>
                <button  className='bg-[#297B41]  text-md font-bold w-full max-w-xs md:py-2 md:px-12 px-20 py-2  rounded-full text-white hover:bg-[#D3EEE1] hover:border-2 border-[#297B41] hover:text-[#297B41]' onClick={()=>navigate("/signup")}>Get Started</button>
                <button className='border-2 border-[#297B41] text-md font-bold   w-full max-w-xs text-[#297B41] md:py-2 md:px-12 px-20 py-2 rounded-full  hover:bg-[#297B41] hover:text-white ' onClick={()=>navigate("/login")}> Log in</button>
                </div>
                </div>
                <div className='mt-20 '>
                    {selectedFood &&(
                        <div className=' fixed inset-0 bg-black/40 backdrop-blur-sm  overflow-y-auto flex items-center justify-center p-4 z-50 '>
                            <div className='bg-white rounded-3xl shadow-2xl   max-w-2xl w-full  max-h-[90vh] overflow-y-auto  p-12 relative  '>
                                <button onClick={()=>setSelectedFood(null)} className='absolute  top-4 right-5   text-3xl font-bold bg-[black] text-white rounded-full z-10 '>
                                        <IoIosClose />
                                </button>
                                <div className='flex flex-col md:flex-row items-center  gap-8 '>
                                    <img src={selectedFood.image} alt={selectedFood.title} className='w-64 h-64 object-cover rounded-2xl shadow-md' >
                                    </img>
                                    <div className='flex-1'>
                                        <h3 className='text-2xl text-center md:text-start md:text-4xl font-bold  mb-4'>
                                            {selectedFood.title}
                                        </h3>
                                        <p className=' text-gray-600 leading-relaxed mb-6'>
                                            {selectedFood.description}
                                        </p>
                                        <div className='border-t pt-5 '>
                                            <h2 className='text-xl font-semibold mb-4'>
                                                Start cooking by creating an account
                                            </h2>
                                            <div className='flex flex-wrap gap-4'>
                                                <button className='bg-[#297B41] text-white px-6 py-2 rounded-full hover:bg-green-700 transition duration-300' onClick={()=>navigate("/signup")}>
                                                    Signup
                                                </button>
                                                <button className='bg-[#297B41] text-white px-6 py-2 rounded-full hover:bg-green-700 transition duration-300' onClick={()=>navigate("/login")}>
                                                    Login
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                            
                              
                    )}
                    
                    <h2 className=' text-center text-4xl font-bold mb-12' >Popular Searches</h2>
                    
                    <div className=' grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-4 gap-6 '>
                        {Foods.map((food,index)=>(
                            <div key={index} className='bg-[white] flex  flex-col items-center rounded-3xl p-4 gap-4 shadow-md hover:shadow-2xl hover:-translate-y-2 transition-all duration-300 cursor-pointer' onClick={()=>setSelectedFood(food)}>
                                <img src={food.image} className=' w-full max-w-[250px] object-cover h-64 rounded-xl'></img>
                                <h3 className='text-2xl font-bold'>{food.title}</h3>
                                <p className='text-gray-600 leading-relaxed mb-6'>{food.description}</p>
                            </div>
                        ))}
                    </div>
                </div>
                

             
        </div>
             
            
        
           
            
           
       
    )
}
export default Home